---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kali-gui
  ansible.builtin.systemd:
    name: kali-gui.service
    state: restarted
  when: kali_install_wayvnc | bool
